### PR TITLE
Fix homebrew pathing related to libomp

### PR DESCRIPTION
**Pull request by phated**
When setting up noir, I was getting build failures with the native backend. This seems to be related to bad pathing on homebrew installations.

When I installed `libomp` with homebrew, I got this message:
> libomp is keg-only, which means it was not symlinked into /Users/phated/brew, because it can override GCC headers and result in broken builds.

This means that libomp wasn't symlinked into the `/Users/phated/brew/lib` directory where the cmake files expected it. I've changed it to the result of `brew --prefix libomp` which is the actual installation location.

Additionally, the `build.rs` file has a hardcoded homebrew location, instead of using the brew prefix, so I fixed that.

### CODE REVIEW

**Review by jfecher — COMMENTED** [review]
I can confirm this builds correctly on my M1 Pro as well

**Review by jfecher — COMMENTED** [review]
This PR looks fine to me but I'd like more people to test building it before merging. So far it is compiling on my M1 Pro, and I cannot test on my linux machine as that is still failing from the lack of relevant header includes.

**Comment by phated** [comment]
@jfecher this should only affect Mac operating systems, everything is guarded by some sort of "apple" checks

**Comment by phated** [comment]
There's an additional argument to be made that `INTEL_APPLE` case should also be using `brew --prefix` but it'd require an intel mac + non-default homebrew setup to test it.

**Comment by vezenovm** [comment]
I am able to build locally on my intel mac from this branch. I can test changing `INTEL_APPLE` to use `brew --prefix` as well in a moment

**Comment by vezenovm** [comment]
> I am able to build locally on my intel mac from this branch. I can test changing `INTEL_APPLE` to use `brew --prefix` as well in a moment

So it does build when I use `find_brew_prefix` for the `INTEL_APPLE` case. Running `brew --prefix` locally gives me `/usr/local`, so I replaced this in PR #12. I branched off of this PR, once you take a look feel free to merge it into this branch.

**Comment by phated** [comment]
Thanks for testing and adding the intel mac patch @vezenovm 🙇 This should be ready for approvals

**Review by kobyhallx — APPROVED** [review]
LGTM 👍

**Pull request merged**
